spring:
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/home/mr_bhat/workspace/gitlab/spring/graphQl-practise/src/main/resources/dbBackup/backup

    username: sa
    password:
  h2:
    console:
      enabled: true
logging:
  level:
    '[org.hibernate]': error
